apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: savvyminds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: savvyminds
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

#use this below to port forward and access the service
#kubectl port-forward service/nginx-service 8080:80
